name: Build STM32F412RG Firmware

on:
  push:
    branches:
      - stm32f412RGT6
  pull_request:
    branches:
      - stm32f412RGT6

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive # 确保子模块被正确更新

    # Install dependencies
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential gcc-arm-none-eabi libnewlib-arm-none-eabi libffi-dev git python3

    # Update submodules
    - name: Update submodules
      run: git submodule update --init --recursive

    # Build mpy-cross
    - name: Build mpy-cross
      run: make -C mpy-cross

    # Build firmware for STM32F412RG
    - name: Build firmware
      run: |
        make -C ports/stm32 BOARD=STM32F412RG clean
        make -C ports/stm32 BOARD=STM32F412RG
      env:
        PATH: /usr/bin:$PATH

    # Upload firmware as an artifact
    - name: Upload firmware
      uses: actions/upload-artifact@v3
      with:
        name: stm32f412rg-firmware
        path: ports/stm32/build-STM32F412RG/firmware.bin
