name: Build STM32F412RG Firmware

on:
  push:
    branches:
      - stm32f412RGT6
  pull_request:
    branches:
      - stm32f412RGT6
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        board: [STM32f412RG]
    steps:
    - uses: actions/checkout@v2
    - name: arm-none-eabi-gcc
      uses: carlosperate/arm-none-eabi-gcc-action@v1.3.0
      with:
        release: '9-2019-q4' # The arm-none-eabi-gcc release to use.
    - name: Update submodules
      run: git submodule update --init --recursive  
    - name: Build mpy-cross
      run: make -j $(nproc) -C mpy-cross
    - name: Build ${{ matrix.board }}
      run: make -j $(nproc) -C ports/stm32 BOARD=${{ matrix.board }}
    - uses: actions/upload-artifact@v2
      if: ${{ env.GITHUB_EVENT_NAME }} == 'push'
      with:
        name: ${{ matrix.board }}.hex
        path: ports/stm32/build-${{ matrix.board }}/firmware.hex
