name: Build STM32F412RG Firmware

on:
  push:
    branches:
      - stm32f412RGT6
  pull_request:
    branches:
      - stm32f412RGT6

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [STM32F412RG] # Ensure this matches your board directory name in ports/stm32/boards
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install ARM GCC Toolchain
      uses: carlosperate/arm-none-eabi-gcc-action@v1.3.0
      with:
        release: '9-2019-q4' # Update if compatibility issues arise

    - name: Update Submodules
      run: git submodule update --init --recursive  

    - name: Build mpy-cross
      run: make -j $(nproc) -C mpy-cross

    - name: Build Firmware
      run: make -j $(nproc) -C ports/stm32 BOARD=${{ matrix.board }} V=1

    - name: Upload Firmware Artifact
      uses: actions/upload-artifact@v2
      if: ${{ github.event_name == 'push' }}
      with:
        name: ${{ matrix.board }}.hex
        path: ports/stm32/build-${{ matrix.board }}/firmware.hex

