name: Build STM32F412

on:
  push:
    branches:
      - stm32f412RGT6
  pull_request:
    branches:
      - stm32f412RGT6

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive  # 确保子模块递归克隆

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y gcc-arm-none-eabi libnewlib-arm-none-eabi python3 git make  # 安装必要的依赖项

    - name: Build mpy-cross
      run: make -C mpy-cross

    - name: Build STM32 firmware
      run: |
        cd ports/stm32
        make BOARD=STM32F412RG V=1 \
           CFLAGS="-I../../py -I../../extmod -I../../lib/stm32lib/CMSIS/STM32F4xx/Include -I../../lib/stm32lib/CMSIS/Include"
        
    - name: Upload firmware artifact
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: ports/stm32/build-STM32F412RG/firmware.bin
